### ISSUE TITLE
Move `Actions::CreateUser` to `UsersController::Action::Create`.

### ISSUE THREAD

**Issue by jdickey** [jdickey/new_poc#205]
In theory, this should be straightforward; in practice… there is always significant variation of practice from theory. :unamused: 

What we should have at the end of this is

* the current `Actions::CreateUser` class moved to a (new, obviously) `UsersController::Action::Create` class;
* all private methods presently in `Actions::CreateUser` restructured, generally following [this comment](https://github.com/jdickey/new_poc/issues/54#issuecomment-74296328) on Issue #54 — point being to make the public action-class API as black a box as reasonably practical;
* a documented effort to think about how to package/share boilerplate code that is known/believed likely to be usable in other Action classes; and finally
* enough (virtual) lab-notebook scrawling that I can understand how I did all of the above when going on to the *next* action, with a view towards iterative improvement of the process. (We do, after all, have a total of ~15 actions to convert.)

**Comment by jdickey** [comment]
The current [`Actions::CreateUser:#initialize` code](https://github.com/jdickey/new_poc/blob/cde66f6/app/actions/create_user.rb#L40-L47) is a *mess*. Bearing in mind what I [just said](https://github.com/jdickey/new_poc/issues/54#issuecomment-75439727) about small, discrete, *visible* steps towards progress, the [Pottery Barn rule](http://en.wikipedia.org/wiki/Pottery_Barn_rule) applies. There's an internal support class in there, down on its knees begging and screaming to be broken out, and we really should put it out of our misery.

**Comment by jdickey** [comment]
...and in that vein, we notice that the `current_user` initialiser parameter and attribute in `Actions::CreateUser` is *only* used in relation to [`#require_guest_user`](https://github.com/jdickey/new_poc/blob/cde66f6/app/actions/create_user.rb#L108-L111) and its support method, [`#already_logged_in_message](https://github.com/jdickey/new_poc/blob/cde66f6/app/actions/create_user.rb#L132-L134). There's also a [`#guest_user_name` method](https://github.com/jdickey/new_poc/blob/cde66f6/app/actions/create_user.rb#L73-L75) with a variably scrutable comment that should also tag along with the others.

**Comment by jdickey** [comment]
...and screw it; let's iterate the *right way*, starting with as literal and direct a transplant as practical and *then* refactoring out the smelly parts.

**Comment by jdickey** [comment]
Well,, that was a "fun" way to spin wheels for a day.

(Nearly) everything associated with the [`#create` action](https://github.com/jdickey/new_poc/blob/a2cea5e/app/controllers/users_controller.rb#L29-L32) on `UsersController` now breaks; untouched controller specs now insist that there *is* no `#create` action defined — until you run [`users_controller_spec.rb`](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb) by itself, which gives you a green bar.

As the [commit message](https://github.com/jdickey/new_poc/commit/a2cea5e) says:

> Hilarity ensues. Specs for `UsersController` and `UsersController::Action::Create` green when run individually, but red when running as part of larger selection (either `spec/controllers` or the entire suite). Many of these failures are `AbstractController::ActionNotFound` errors stating that "The action
> 'create' could not be found for UsersController".
>
> Head-scratching in progress.

(Those for `UsersController` red when run as part of a larger group; new `UsersController::Action::Create` stays green. For whatever *that's* worth.)

Anybody?

**Comment by jdickey** [comment]
Elaborating on the above, running `bundle exec rspec spec/controllers --order defined` against Commit a2cea5e yields the following error output:

```
Failures:

  1) UsersController GET 'index' assigns the non-Guest users to the :users item
     Failure/Error: index_user = index_users[index]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/controllers/users_controller_spec.rb:63:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/users_controller_spec.rb:62:in `each'
     # ./spec/controllers/users_controller_spec.rb:62:in `each_with_index'
     # ./spec/controllers/users_controller_spec.rb:62:in `block (3 levels) in <top (required)>'

  2) UsersController GET 'new' with no user logged in assigns a User entity instance to :user
     Failure/Error: expect(assigns[:user]).to be_a Newpoc::Entity::User
       expected nil to be a kind of Newpoc::Entity::User
     # ./spec/controllers/users_controller_spec.rb:82:in `block (4 levels) in <top (required)>'

  3) UsersController GET 'new' with a user logged in redirects to the root path
     Failure/Error: expect(response).to redirect_to root_path
       Expected response to be a <redirect>, but was <200>
     # ./spec/controllers/users_controller_spec.rb:104:in `block (4 levels) in <top (required)>'

  4) UsersController GET 'new' with a user logged in has the correct flash message
     Failure/Error: expect(flash[:alert]).to eq "Already logged in as #{user.name}!"
       
       expected: "Already logged in as J Random User Number 96!"
            got: nil
       
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:108:in `block (4 levels) in <top (required)>'

  5) UsersController POST 'create' with valid parameters assigns the :user item as a User entity instance
     Failure/Error: post :create, user_data: params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:118:in `block (4 levels) in <top (required)>'

  6) UsersController POST 'create' with valid parameters persists the User entity corresponding to the :user
     Failure/Error: post :create, user_data: params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:118:in `block (4 levels) in <top (required)>'

  7) UsersController POST 'create' with valid parameters redirects to the root path
     Failure/Error: post :create, user_data: params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:118:in `block (4 levels) in <top (required)>'

  8) UsersController POST 'create' with valid parameters displays the "Thank you for signing up!" flash message
     Failure/Error: post :create, user_data: params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:118:in `block (4 levels) in <top (required)>'

  9) UsersController POST 'create' with invalid parameters that result in an apparently valid user entity, such as a duplicate name assigns a User entity to :user
     Failure/Error: post :create, user_data: params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:146:in `block (6 levels) in <top (required)>'

  10) UsersController POST 'create' with invalid parameters that result in an apparently valid user entity, such as a duplicate name does not redirect
     Failure/Error: post :create, user_data: params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:146:in `block (6 levels) in <top (required)>'

  11) UsersController POST 'create' with invalid parameters that result in an apparently valid user entity, such as a duplicate name adds the name-already-taken error message to the :user entity
     Failure/Error: post :create, user_data: params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:146:in `block (6 levels) in <top (required)>'

  12) UsersController POST 'create' with invalid parameters that result in a visibly invalid user entity, including an empty name
     Failure/Error: post :create, user_data: @params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:172:in `block (5 levels) in <top (required)>'

  13) UsersController POST 'create' with invalid parameters that result in a visibly invalid user entity, including an invalid email address
     Failure/Error: post :create, user_data: @params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:172:in `block (5 levels) in <top (required)>'

  14) UsersController POST 'create' with invalid parameters that result in a visibly valid user entity, including mismatched passwords
     Failure/Error: post :create, user_data: @params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:201:in `block (5 levels) in <top (required)>'

  15) UsersController POST 'create' with invalid parameters that result in a visibly valid user entity, including too short passwords
     Failure/Error: post :create, user_data: @params
     AbstractController::ActionNotFound:
       The action 'create' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:201:in `block (5 levels) in <top (required)>'

  16) UsersController GET 'edit' for the Guest User displays the authorisation-failure flash message
     Failure/Error: expect(request.flash[:alert]).to eq not_auth_message
       
       expected: "Not logged in as J Random User Number 108!"
            got: nil
       
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:247:in `block (4 levels) in <top (required)>'

  17) UsersController GET 'edit' for the Guest User redirects to the root path
     Failure/Error: expect(response).to redirect_to root_path
       Expected response to be a <redirect>, but was <200>
     # ./spec/controllers/users_controller_spec.rb:251:in `block (4 levels) in <top (required)>'

  18) UsersController GET 'edit' for the logged-in user editing his own record assigns the :user variable to the logged-in user entity
     Failure/Error: expect(assigns[:user]).to eq user
       
       expected: #<UserDao id: 108083, name: "J Random User Number 112", slug: "j-random-user-number-112", password_digest: "$2a$04$PHTIw58/oU81pV7kpJTd5.04ILqJODdI3MPCFuBhW9K...", email: "jruser115@example.com", profile: "Just Another *Random* User", created_at: "2015-02-24 06:38:18", updated_at: "2015-02-24 06:38:18">
            got: nil
       
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:275:in `block (5 levels) in <top (required)>'

  19) UsersController GET 'edit' for the logged-in user attempting to edit the record of another user redirects to the root path
     Failure/Error: expect(response).to redirect_to root_path
       Expected response to be a <redirect>, but was <200>
     # ./spec/controllers/users_controller_spec.rb:288:in `block (5 levels) in <top (required)>'

  20) UsersController GET 'edit' for the logged-in user attempting to edit the record of another user displays the authorisation-failure flash message
     Failure/Error: expect(request.flash[:alert]).to eq not_auth_message
       
       expected: "Not logged in as J Random User Number 116!"
            got: nil
       
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:292:in `block (5 levels) in <top (required)>'

  21) UsersController GET 'show' succeeds in requesting any existing public profile, so that it assigns the target user to the :user variable
     Failure/Error: expect(assigns[:user]).to eq target_user
       
       expected: #<Newpoc::Entity::User:0x007f93ebb963e8 @markdown_converter=#<Proc:0x007f93ebb96370@/Users/jeffdickey/src/rails/meldd/new_poc/lib/newpoc-entity-user/lib/newpoc/entity/user.rb:97 (lambda)>, @name="J Random User Number 117", @email="jruser120@example.com", @slug="j-random-user-number-117", @updated_at=nil, @profile="Just Another *Random* User", @created_at=2015-02-24 14:38:18 +0800, @password="password", @password_confirmation="password">
            got: nil
       
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:313:in `block (4 levels) in <top (required)>'

  22) UsersController GET 'show' when attempting to view a profile which does not exist, is redirected to the user-index page
     Failure/Error: expect(response).to redirect_to users_path
       Expected response to be a <redirect>, but was <200>
     # ./spec/controllers/users_controller_spec.rb:329:in `block (4 levels) in <top (required)>'

  23) UsersController GET 'show' when attempting to view a profile which does not exist, is shown the correct flash error message
     Failure/Error: expect(flash[:alert]).to eq message
       
       expected: "Cannot find user identified by slug invalid-user-slug!"
            got: nil
       
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:334:in `block (4 levels) in <top (required)>'

  24) UsersController PATCH 'update' for a logged-in user assigns the updated user record
     Failure/Error: patch :update, params
     AbstractController::ActionNotFound:
       The action 'update' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:353:in `block (4 levels) in <top (required)>'

  25) UsersController PATCH 'update' for a logged-in user redirects to the user profile page
     Failure/Error: patch :update, params
     AbstractController::ActionNotFound:
       The action 'update' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:353:in `block (4 levels) in <top (required)>'

  26) UsersController PATCH 'update' for a logged-in user has the correct flash message
     Failure/Error: patch :update, params
     AbstractController::ActionNotFound:
       The action 'update' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:353:in `block (4 levels) in <top (required)>'

  27) UsersController PATCH 'update' for the Guest User redirects to the landing page
     Failure/Error: patch :update, params
     AbstractController::ActionNotFound:
       The action 'update' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:381:in `block (4 levels) in <top (required)>'

  28) UsersController PATCH 'update' for the Guest User does not modify the user record
     Failure/Error: patch :update, params
     AbstractController::ActionNotFound:
       The action 'update' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:381:in `block (4 levels) in <top (required)>'

  29) UsersController PATCH 'update' for the Guest User has the correct flash message
     Failure/Error: patch :update, params
     AbstractController::ActionNotFound:
       The action 'update' could not be found for UsersController
     # ./spec/controllers/users_controller_spec.rb:381:in `block (4 levels) in <top (required)>'
```

----

Specifically,

* 15 of the 29 failures are `AbstractController::ActionNotFound` errors being raised saying that "The action 'create' could not be found for UsersController". These were on spec lines [118](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L118) (4x); [146](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L146) (3x); [172](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L172) (2x); [201](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L201) (2x);
* 2 of the 29 failures are `AbstractController::ActionNotFound` errors being raised saying that "The action 'update' could not be found for UsersController". These were on spec lines  [353](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L353) (3x); and [381](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L381) (3x);
* 8 of the 29 are where some object or value was expected to exist but didn't (and thus was `nil`). See spec lines [63](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L63), [82](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L82), [108](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L108), [247](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L247), [275](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L275), [292](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L292), [313](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L313), and [334](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L334);
* The remaining three failures (at lines [104](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L104), [288](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L288) and [329](https://github.com/jdickey/new_poc/blob/a2cea5e/spec/controllers/users_controller_spec.rb#L329) are all failed expectations that the controller response would be a redirect, but HTTP status 200 (OK) was received instead.

My strong suspicion is that if we solve the "missing action" problems, the others will be solved as well.

**Comment by jdickey** [comment]
Just to save both of you the trip to check, those `ActionNotFound` errors are raised for *every* `:create` or `:update` action currently in the spec. 

Also, changing the [`UserController#create` action](https://github.com/jdickey/new_poc/blob/a2cea5e0de34d02e92a7482e141b474117c2cf99/app/controllers/users_controller.rb#L29-L32) back to the previous use of `Actions::CreateUser` has *no apparent effect* on the errors. *Deeply* confused. :confused:

**Comment by jdickey** [comment]
Whee! The last ~12 hours have been fun, once I got back to basics (which required a rebundle, which killed four otherwise perfectly usable hours).

As the last commit said, a *lot* of (now-)[internal support classes](https://github.com/jdickey/new_poc/tree/d9927c5/app/controllers/users_controller/action/create/internals) that are likely to get reused, and a new [`Broadcaster` module](https://github.com/jdickey/new_poc/blob/d9927c5/app/controllers/users_controller/action/create/broadcaster.rb) that will be reused *pervasively* in every class that broadcasts Wisper success/failure notifications.

It's been a good day, for a change.
